package identity

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/gophercloud/gophercloud/v2"
	"github.com/gophercloud/gophercloud/v2/openstack/identity/v3/applicationcredentials"
	"github.com/gophercloud/gophercloud/v2/openstack/identity/v3/tokens"
	"github.com/spf13/cobra"

	"github.com/ftarasenko/go-openstackclient/internal/auth"
	"github.com/ftarasenko/go-openstackclient/internal/output"
)

// Flag names follow upstream OSC (`openstack application credential ...`).
// UNVERIFIED against KeyStack docs (https://docs.keystack.ru/ returned HTTP 403
// at implementation time); falls back to upstream OSC semantics.
//
// Application credentials are nested under a user in keystone
// (applicationcredentials.List(client, userID, ...)). When --user is omitted the
// commands operate on the currently authenticated user, whose ID is read from
// the token minted during authentication.

func newApplicationCommand(a *auth.Options, o *output.Options) *cobra.Command {
	// Match OSC's two-word noun by nesting "credential" under "application".
	app := &cobra.Command{Use: "application", Short: "Application credential commands"}
	cred := &cobra.Command{Use: "credential", Short: "Manage application credentials"}
	cred.AddCommand(
		newAppCredListCommand(a, o),
		newAppCredCreateCommand(a, o),
		newAppCredDeleteCommand(a, o),
	)
	app.AddCommand(cred)
	return app
}

// currentUserID reads the authenticated user's ID from the auth result attached
// to the provider during authentication. It is the raw-client fallback used
// where the API needs a user ID but the operator did not supply --user.
func currentUserID(ac *auth.Client) (string, error) {
	res := ac.Provider.GetAuthResult()
	cr, ok := res.(tokens.CreateResult)
	if !ok {
		return "", fmt.Errorf("cannot determine current user: unexpected auth result type %T", res)
	}
	u, err := cr.ExtractUser()
	if err != nil {
		return "", fmt.Errorf("extracting current user from token: %w", err)
	}
	return u.ID, nil
}

// resolveAppCredUser returns the user ID the app-credential command targets:
// the resolved --user value, or the current user when the flag is empty.
func resolveAppCredUser(ctx context.Context, client *gophercloud.ServiceClient, ac *auth.Client, userFlag string) (string, error) {
	if userFlag == "" {
		return currentUserID(ac)
	}
	return resolveUserID(ctx, client, userFlag, "")
}

func newAppCredListCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var user string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List application credentials",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, ac, err := newIdentityAuthClient(ctx, a)
			if err != nil {
				return err
			}
			userID, err := resolveAppCredUser(ctx, client, ac, user)
			if err != nil {
				return err
			}
			return runAppCredList(ctx, client, o, userID, cmd.OutOrStdout())
		},
	}
	cmd.Flags().StringVar(&user, "user", "", "owning user (name or ID; defaults to the current user)")
	return cmd
}

func runAppCredList(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options, userID string, w io.Writer) error {
	pages, err := applicationcredentials.List(client, userID, applicationcredentials.ListOpts{}).AllPages(ctx)
	if err != nil {
		return fmt.Errorf("listing application credentials: %w", err)
	}
	all, err := applicationcredentials.ExtractApplicationCredentials(pages)
	if err != nil {
		return fmt.Errorf("parsing application credential list: %w", err)
	}
	t := output.Table{Columns: []string{"ID", "Name", "Project ID", "Description", "Expires At"}, Rows: make([][]any, 0, len(all))}
	for _, c := range all {
		t.Rows = append(t.Rows, []any{c.ID, c.Name, c.ProjectID, c.Description, formatTime(c.ExpiresAt)})
	}
	return o.WriteList(w, t)
}

type appCredCreateFlags struct {
	user       string
	secret     string
	roles      []string
	expiration string
}

func newAppCredCreateCommand(a *auth.Options, o *output.Options) *cobra.Command {
	f := &appCredCreateFlags{}
	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create a new application credential",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, ac, err := newIdentityAuthClient(ctx, a)
			if err != nil {
				return err
			}
			userID, err := resolveAppCredUser(ctx, client, ac, f.user)
			if err != nil {
				return err
			}
			return runAppCredCreate(ctx, client, o, userID, args[0], f, cmd.OutOrStdout())
		},
	}
	fl := cmd.Flags()
	fl.StringVar(&f.user, "user", "", "owning user (name or ID; defaults to the current user)")
	fl.StringVar(&f.secret, "secret", "", "secret to use (generated by the server if omitted)")
	fl.StringArrayVar(&f.roles, "role", nil, "restrict to a role (name or ID; repeatable)")
	fl.StringVar(&f.expiration, "expiration", "", "expiry time in RFC3339, e.g. 2026-12-31T23:59:59Z")
	return cmd
}

func runAppCredCreate(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options, userID, name string, f *appCredCreateFlags, w io.Writer) error {
	opts := applicationcredentials.CreateOpts{
		Name:   name,
		Secret: f.secret,
	}
	for _, r := range f.roles {
		roleID, err := resolveRoleID(ctx, client, r, "")
		if err != nil {
			return err
		}
		opts.Roles = append(opts.Roles, applicationcredentials.Role{ID: roleID})
	}
	if f.expiration != "" {
		exp, err := time.Parse(time.RFC3339, f.expiration)
		if err != nil {
			return fmt.Errorf("parsing --expiration %q: %w", f.expiration, err)
		}
		opts.ExpiresAt = &exp
	}
	c, err := applicationcredentials.Create(ctx, client, userID, opts).Extract()
	if err != nil {
		return fmt.Errorf("creating application credential %q: %w", name, err)
	}
	return o.WriteSingle(w,
		[]string{"ID", "Name", "Project ID", "Secret", "Expires At"},
		[]any{c.ID, c.Name, c.ProjectID, c.Secret, formatTime(c.ExpiresAt)})
}

func newAppCredDeleteCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var user string
	cmd := &cobra.Command{
		Use:   "delete <application-credential>",
		Short: "Delete an application credential",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, ac, err := newIdentityAuthClient(ctx, a)
			if err != nil {
				return err
			}
			userID, err := resolveAppCredUser(ctx, client, ac, user)
			if err != nil {
				return err
			}
			return runAppCredDelete(ctx, client, userID, args[0])
		},
	}
	cmd.Flags().StringVar(&user, "user", "", "owning user (name or ID; defaults to the current user)")
	return cmd
}

func runAppCredDelete(ctx context.Context, client *gophercloud.ServiceClient, userID, ref string) error {
	id, err := resolveAppCredID(ctx, client, userID, ref)
	if err != nil {
		return err
	}
	if err := applicationcredentials.Delete(ctx, client, userID, id).ExtractErr(); err != nil {
		return fmt.Errorf("deleting application credential %q: %w", ref, err)
	}
	return nil
}

// resolveAppCredID resolves an application credential name to its ID within the
// owning user's credentials. It mirrors the name-or-ID resolvers in resolve.go:
// exactly one name match wins, zero matches falls back to treating ref as an ID,
// and more than one match is ambiguous.
func resolveAppCredID(ctx context.Context, client *gophercloud.ServiceClient, userID, ref string) (string, error) {
	pages, err := applicationcredentials.List(client, userID, applicationcredentials.ListOpts{Name: ref}).AllPages(ctx)
	if err != nil {
		return "", fmt.Errorf("resolving application credential %q: %w", ref, err)
	}
	all, err := applicationcredentials.ExtractApplicationCredentials(pages)
	if err != nil {
		return "", fmt.Errorf("parsing application credential list: %w", err)
	}
	switch len(all) {
	case 0:
		return ref, nil
	case 1:
		return all[0].ID, nil
	default:
		return "", fmt.Errorf("application credential name %q is ambiguous: %d matches", ref, len(all))
	}
}

func formatTime(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format(time.RFC3339)
}
