package placement

import (
	"context"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/gophercloud/gophercloud/v2"
	"github.com/gophercloud/gophercloud/v2/openstack/placement/v1/allocationcandidates"
	"github.com/gophercloud/gophercloud/v2/openstack/placement/v1/allocations"
	"github.com/gophercloud/gophercloud/v2/openstack/placement/v1/resourceproviders"
	"github.com/gophercloud/gophercloud/v2/openstack/placement/v1/traits"
	"github.com/gophercloud/gophercloud/v2/openstack/placement/v1/usages"
	"github.com/spf13/cobra"

	"github.com/ftarasenko/go-openstackclient/internal/auth"
	"github.com/ftarasenko/go-openstackclient/internal/cli/batchdelete"
	"github.com/ftarasenko/go-openstackclient/internal/output"
)

// The placement write surface: resource-provider create/set, inventory and
// trait writes, aggregate membership, consumer allocations, and the two
// read-only nouns that were missing (allocation candidates, project usage).
//
// Verb and flag names mirror upstream osc-placement. UNVERIFIED against
// KeyStack docs (https://docs.keystack.ru/ returned HTTP 403 at implementation
// time); falls back to upstream semantics.

// --- resource provider create / set -----------------------------------------

func newProviderCreateCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var uuid, parent string
	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create a resource provider",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderCreate(ctx, client, o, args[0], uuid, parent, cmd.OutOrStdout())
		},
	}
	fl := cmd.Flags()
	fl.StringVar(&uuid, "uuid", "", "UUID for the provider (default: generated by placement)")
	fl.StringVar(&parent, flagParentProvider, "", "UUID of the parent provider (placement 1.14 or later)")
	return cmd
}

func runProviderCreate(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	name, uuid, parent string, w io.Writer,
) error {
	rp, err := resourceproviders.Create(ctx, client, resourceproviders.CreateOpts{
		Name:               name,
		UUID:               uuid,
		ParentProviderUUID: parent,
	}).Extract()
	if err != nil {
		return fmt.Errorf("creating resource provider %q: %w", name, err)
	}
	return writeProvider(o, w, rp)
}

type providerSetFlags struct {
	name   string
	parent string

	// Which were given: an explicitly empty --parent-provider re-roots the
	// provider, so it is not the same as omitting the flag.
	nameSet   bool
	parentSet bool
}

func newProviderSetCommand(a *auth.Options, o *output.Options) *cobra.Command {
	f := &providerSetFlags{}
	cmd := &cobra.Command{
		Use:   useSetUUID,
		Short: "Set resource provider properties",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			fl := cmd.Flags()
			if !fl.Changed("name") && !fl.Changed(flagParentProvider) {
				return fmt.Errorf("resource provider set requires --name or --parent-provider")
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			f.nameSet, f.parentSet = fl.Changed("name"), fl.Changed(flagParentProvider)
			return runProviderSet(ctx, client, o, args[0], f, cmd.OutOrStdout())
		},
	}
	fl := cmd.Flags()
	fl.StringVar(&f.name, "name", "", "new provider name")
	fl.StringVar(&f.parent, flagParentProvider, "",
		"UUID of the new parent provider; empty makes it a root provider (placement 1.37 or later)")
	return cmd
}

func runProviderSet(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	id string, f *providerSetFlags, w io.Writer,
) error {
	opts := resourceproviders.UpdateOpts{}
	if f.nameSet {
		opts.Name = &f.name
	}
	// Both fields are pointers so an explicit empty value stays distinguishable
	// from an omitted flag on the wire.
	if f.parentSet {
		opts.ParentProviderUUID = &f.parent
	}
	rp, err := resourceproviders.Update(ctx, client, id, opts).Extract()
	if err != nil {
		return fmt.Errorf("updating resource provider %s: %w", id, err)
	}
	return writeProvider(o, w, rp)
}

func writeProvider(o *output.Options, w io.Writer, rp *resourceproviders.ResourceProvider) error {
	return o.WriteSingle(w,
		[]string{"uuid", "name", "generation", "parent_provider_uuid", "root_provider_uuid"},
		[]any{rp.UUID, rp.Name, rp.Generation, rp.ParentProviderUUID, rp.RootProviderUUID})
}

// --- inventory writes -------------------------------------------------------

// inventoryBody is the set of inventory fields the operator actually named.
//
// It is a map rather than resourceproviders.Inventory because that struct tags
// none of its fields omitempty, so gophercloud's BuildRequestBody serialises the
// whole set — and an unmentioned integer serialises as 0. Placement's schema
// puts a `minimum: 1` on step_size, min_unit and max_unit, so a request built
// from the struct is rejected outright:
//
//	JSON does not validate: 0 is less than the minimum of 1
//
// which made both inventory verbs unusable unless the operator spelled out every
// field. Sending only what was asked for lets placement apply its own defaults,
// which is what upstream osc-placement does.
type inventoryBody map[string]any

// parseInventory parses the key=value pairs shared by the inventory verbs.
// Placement's inventory object is a fixed set of integers plus a float ratio,
// so an unknown key is a typo worth catching before the round trip.
func parseInventory(pairs []string) (inventoryBody, error) {
	inv := inventoryBody{}
	for _, p := range pairs {
		k, v, ok := strings.Cut(p, "=")
		if !ok {
			return inv, fmt.Errorf("expected key=value, got %q", p)
		}
		key := strings.TrimSpace(k)
		switch key {
		case "total", "reserved", "min_unit", "max_unit", "step_size":
			n, err := strconv.Atoi(v)
			if err != nil {
				return inv, fmt.Errorf("%s: %w", key, err)
			}
			inv[key] = n
		case "allocation_ratio":
			f, err := strconv.ParseFloat(v, 32)
			if err != nil {
				return inv, fmt.Errorf("allocation_ratio: %w", err)
			}
			inv[key] = float32(f)
		default:
			return inv, fmt.Errorf("unknown inventory field %q; placement defines total, reserved, "+
				"min_unit, max_unit, step_size and allocation_ratio", key)
		}
	}
	return inv, nil
}

// updateInventoryOpts builds the body for one resource class. It satisfies
// resourceproviders.UpdateInventoryOptsBuilder so the vendored request function
// can still be used; only the body construction is koc's.
type updateInventoryOpts struct {
	generation int
	fields     inventoryBody
}

func (o updateInventoryOpts) ToResourceProviderUpdateInventoryMap() (map[string]any, error) {
	b := map[string]any{"resource_provider_generation": o.generation}
	for k, v := range o.fields {
		b[k] = v
	}
	return b, nil
}

// updateInventoriesOpts builds the whole-provider body, same reasoning.
type updateInventoriesOpts struct {
	generation  int
	inventories map[string]inventoryBody
}

func (o updateInventoriesOpts) ToResourceProviderUpdateInventoriesMap() (map[string]any, error) {
	inv := make(map[string]any, len(o.inventories))
	for class, fields := range o.inventories {
		inv[class] = map[string]any(fields)
	}
	return map[string]any{
		"resource_provider_generation": o.generation,
		"inventories":                  inv,
	}, nil
}

// inventoryFieldNames are the inventory fields placement defines, in the order
// upstream osc-placement lists them as flags.
var inventoryFieldNames = []struct{ name, usage string }{
	{"total", "total amount of the resource the provider offers"},
	{"reserved", "amount held back from allocation"},
	{"min_unit", "smallest allocatable amount"},
	{"max_unit", "largest allocatable amount"},
	{"step_size", "allocations must be a multiple of this"},
	{"allocation_ratio", "over-subscription ratio"},
}

func newProviderInventoryClassSetCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var fields []string
	// Upstream osc-placement spells the fields as one flag each (--total, and so
	// on) rather than koc's --resource key=value; both are accepted so an upstream
	// command line works verbatim. They are strings, not ints, so that "not given"
	// stays distinguishable from an explicit 0 — placement treats an absent field
	// as "apply the default", which is not the same thing.
	named := make([]string, len(inventoryFieldNames))
	class := &cobra.Command{
		Use:   "set <uuid> <resource-class>",
		Short: "Replace one resource class's inventory on a provider",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			all := append([]string{}, fields...)
			for i, f := range inventoryFieldNames {
				if named[i] != "" {
					all = append(all, f.name+"="+named[i])
				}
			}
			return runProviderInventoryClassSet(ctx, client, o, args[0], args[1], all, cmd.OutOrStdout())
		},
	}
	class.Flags().StringArrayVar(&fields, "resource", nil,
		"inventory field as key=value, e.g. total=64 (repeatable)")
	for i, f := range inventoryFieldNames {
		class.Flags().StringVar(&named[i], f.name, "", f.usage)
	}
	cmd := &cobra.Command{Use: "class", Short: "Manage one resource class's inventory"}
	cmd.AddCommand(class)
	return cmd
}

func runProviderInventoryClassSet(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	id, class string, fields []string, w io.Writer,
) error {
	inv, err := parseInventory(fields)
	if err != nil {
		return fmt.Errorf("parsing --resource: %w", err)
	}
	if len(inv) == 0 {
		return fmt.Errorf("nothing to set on %s inventory: give --total (or another inventory field)", class)
	}
	// Placement requires the provider's current generation on this write and
	// rejects a stale one with 409. Reading it here is what makes two writes in a
	// row work without the caller re-reading in between.
	current, err := resourceproviders.GetInventories(ctx, client, id).Extract()
	if err != nil {
		return fmt.Errorf("reading resource provider %s before writing its inventory: %w", id, err)
	}
	got, err := resourceproviders.UpdateInventory(ctx, client, id, class,
		updateInventoryOpts{generation: current.ResourceProviderGeneration, fields: inv}).Extract()
	if err != nil {
		return fmt.Errorf("setting %s inventory on resource provider %s: %w", class, id, err)
	}
	return o.WriteSingle(w,
		[]string{"resource_class", "total", "reserved", "min_unit", "max_unit", "step_size", "allocation_ratio"},
		[]any{class, got.Total, got.Reserved, got.MinUnit, got.MaxUnit, got.StepSize, got.AllocationRatio})
}

func newProviderInventorySetCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var resources []string
	cmd := &cobra.Command{
		Use:   useSetUUID,
		Short: "Replace a provider's entire inventory",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderInventorySet(ctx, client, o, args[0], resources, cmd.OutOrStdout())
		},
	}
	cmd.Flags().StringArrayVar(&resources, "resource", nil,
		"inventory entry as CLASS:field=value, e.g. VCPU:total=16 (repeatable)")
	return cmd
}

// runProviderInventorySet replaces every inventory record on the provider, so
// a class left out of --resource is removed. That is placement's PUT semantics
// and upstream's too; the generation is read first because placement rejects
// the write without a current one.
func runProviderInventorySet(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	id string, resources []string, w io.Writer,
) error {
	byClass := map[string][]string{}
	for _, spec := range resources {
		class, field, ok := strings.Cut(spec, ":")
		if !ok {
			// Upstream documents CLASS=VALUE as shorthand for CLASS:total=VALUE
			// ("--resource VCPU=16 is equivalent to --resource VCPU:total=16"), so
			// the bare form is the common one in practice.
			class, value, isPair := strings.Cut(spec, "=")
			if !isPair {
				return fmt.Errorf("expected CLASS:field=value or CLASS=total, got %q", spec)
			}
			byClass[class] = append(byClass[class], "total="+value)
			continue
		}
		byClass[class] = append(byClass[class], field)
	}
	inventories := map[string]inventoryBody{}
	for class, fields := range byClass {
		inv, err := parseInventory(fields)
		if err != nil {
			return fmt.Errorf("parsing --resource for %s: %w", class, err)
		}
		inventories[class] = inv
	}

	current, err := resourceproviders.GetInventories(ctx, client, id).Extract()
	if err != nil {
		return fmt.Errorf("reading resource provider %s before writing its inventory: %w", id, err)
	}
	got, err := resourceproviders.UpdateInventories(ctx, client, id, updateInventoriesOpts{
		generation:  current.ResourceProviderGeneration,
		inventories: inventories,
	}).Extract()
	if err != nil {
		return fmt.Errorf("setting the inventory of resource provider %s: %w", id, err)
	}
	return writeInventories(o, w, got.Inventories)
}

func newProviderInventoryDeleteCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var class string
	cmd := &cobra.Command{
		Use:   "delete <uuid>",
		Short: "Delete a provider's inventory",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderInventoryDelete(ctx, client, args[0], class)
		},
	}
	cmd.Flags().StringVar(&class, "resource-class", "",
		"delete only this class's inventory (default: every class)")
	return cmd
}

func runProviderInventoryDelete(ctx context.Context, client *gophercloud.ServiceClient, id, class string) error {
	if class != "" {
		if err := resourceproviders.DeleteInventory(ctx, client, id, class).ExtractErr(); err != nil {
			return fmt.Errorf("deleting %s inventory from resource provider %s: %w", class, id, err)
		}
		return nil
	}
	if err := resourceproviders.DeleteInventories(ctx, client, id).ExtractErr(); err != nil {
		return fmt.Errorf("deleting the inventory of resource provider %s: %w", id, err)
	}
	return nil
}

func writeInventories(o *output.Options, w io.Writer, inventories map[string]resourceproviders.Inventory) error {
	t := output.Table{
		Columns: []string{colResourceClass, "Total", "Reserved", "Min Unit", "Max Unit", "Step Size", "Allocation Ratio"},
	}
	for class, inv := range inventories {
		t.Rows = append(t.Rows, []any{class, inv.Total, inv.Reserved, inv.MinUnit, inv.MaxUnit, inv.StepSize, inv.AllocationRatio})
	}
	sortRowsByFirstColumn(t.Rows)
	return o.WriteList(w, t)
}

// --- trait writes on a provider ---------------------------------------------

func newProviderTraitSetCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var traitNames []string
	cmd := &cobra.Command{
		Use:   useSetUUID,
		Short: "Replace the traits on a resource provider",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderTraitSet(ctx, client, o, args[0], traitNames, cmd.OutOrStdout())
		},
	}
	cmd.Flags().StringArrayVar(&traitNames, "trait", nil, "trait to set (repeatable; replaces the existing set)")
	return cmd
}

// runProviderTraitSet replaces the whole trait list — placement's PUT has no
// merge mode — and reads the generation first, which the write requires.
func runProviderTraitSet(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	id string, traitNames []string, w io.Writer,
) error {
	current, err := resourceproviders.GetTraits(ctx, client, id).Extract()
	if err != nil {
		return fmt.Errorf("reading resource provider %s before writing its traits: %w", id, err)
	}
	got, err := resourceproviders.UpdateTraits(ctx, client, id, resourceproviders.UpdateTraitsOpts{
		ResourceProviderGeneration: current.ResourceProviderGeneration,
		Traits:                     traitNames,
	}).Extract()
	if err != nil {
		return fmt.Errorf("setting the traits of resource provider %s: %w", id, err)
	}
	t := output.Table{Columns: []string{"Name"}, Rows: make([][]any, 0, len(got.Traits))}
	for _, name := range got.Traits {
		t.Rows = append(t.Rows, []any{name})
	}
	return o.WriteList(w, t)
}

func newProviderTraitDeleteCommand(a *auth.Options, o *output.Options) *cobra.Command {
	return &cobra.Command{
		Use:   "delete <uuid>",
		Short: "Delete every trait from a resource provider",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderTraitDelete(ctx, client, args[0])
		},
	}
}

func runProviderTraitDelete(ctx context.Context, client *gophercloud.ServiceClient, id string) error {
	if err := resourceproviders.DeleteTraits(ctx, client, id).ExtractErr(); err != nil {
		return fmt.Errorf("deleting the traits of resource provider %s: %w", id, err)
	}
	return nil
}

// --- aggregate set ----------------------------------------------------------

func newProviderAggregateSetCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var aggregates []string
	cmd := &cobra.Command{
		Use:   useSetUUID,
		Short: "Replace the aggregates a resource provider belongs to",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderAggregateSet(ctx, client, o, args[0], aggregates, cmd.OutOrStdout())
		},
	}
	cmd.Flags().StringArrayVar(&aggregates, "aggregate", nil,
		"aggregate UUID (repeatable; replaces the existing set)")
	return cmd
}

func runProviderAggregateSet(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	id string, aggregates []string, w io.Writer,
) error {
	current, err := resourceproviders.GetAggregates(ctx, client, id).Extract()
	if err != nil {
		return fmt.Errorf("reading resource provider %s before writing its aggregates: %w", id, err)
	}
	// UpdateAggregates parses client.Microversion to choose the body shape, so it
	// needs a number rather than koc's negotiated "latest".
	client = concreteClient(ctx, client)
	// The generation is required from placement 1.19; sending the one just read
	// is what makes the write safe against a concurrent change.
	generation := current.ResourceProviderGeneration
	got, err := resourceproviders.UpdateAggregates(ctx, client, id, resourceproviders.UpdateAggregatesOpts{
		ResourceProviderGeneration: generation,
		Aggregates:                 aggregates,
	}).Extract()
	if err != nil {
		return fmt.Errorf("setting the aggregates of resource provider %s: %w", id, err)
	}
	t := output.Table{Columns: []string{"Aggregate UUID"}, Rows: make([][]any, 0, len(got.Aggregates))}
	for _, agg := range got.Aggregates {
		t.Rows = append(t.Rows, []any{agg})
	}
	return o.WriteList(w, t)
}

// --- consumer allocations ---------------------------------------------------

func newProviderAllocationShowCommand(a *auth.Options, o *output.Options) *cobra.Command {
	return &cobra.Command{
		Use:   "show <consumer-uuid>",
		Short: "Show a consumer's allocations",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderAllocationShow(ctx, client, o, args[0], cmd.OutOrStdout())
		},
	}
}

func runProviderAllocationShow(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	consumer string, w io.Writer,
) error {
	got, err := allocations.Get(ctx, client, consumer).Extract()
	if err != nil {
		return fmt.Errorf("showing the allocations of consumer %s: %w", consumer, err)
	}
	t := output.Table{Columns: []string{"Resource Provider", colResourceClass, "Used"}}
	for providerID, alloc := range got.Allocations {
		for class, used := range alloc.Resources {
			t.Rows = append(t.Rows, []any{providerID, class, used})
		}
	}
	sortRowsByFirstColumn(t.Rows)
	return o.WriteList(w, t)
}

type allocationSetFlags struct {
	specs        []string
	projectID    string
	userID       string
	consumerType string
}

func newProviderAllocationSetCommand(a *auth.Options, o *output.Options) *cobra.Command {
	f := &allocationSetFlags{}
	cmd := &cobra.Command{
		Use:   "set <consumer-uuid>",
		Short: "Replace a consumer's allocations",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderAllocationSet(ctx, client, o, args[0], f, cmd.OutOrStdout())
		},
	}
	fl := cmd.Flags()
	fl.StringArrayVar(&f.specs, "allocation", nil,
		"allocation as rp=<provider-uuid>,<CLASS>=<amount> (repeatable)")
	fl.StringVar(&f.projectID, "project-id", "", "project the consumer belongs to")
	fl.StringVar(&f.userID, "user-id", "", "user the consumer belongs to")
	fl.StringVar(&f.consumerType, "consumer-type", "",
		"consumer type, e.g. INSTANCE or MIGRATION (required by placement 1.38+)")
	_ = cmd.MarkFlagRequired("allocation")
	return cmd
}

// consumerTypeMicroversion is where placement made consumer_type a required
// property of the allocations PUT body. Zed's placement already tops out at
// 1.39, so every cloud koc supports is at or above it.
const consumerTypeMicroversion = "1.38"

// requiresConsumerType reports whether the negotiated microversion makes
// consumer_type mandatory. koc's default is "latest", which on any supported
// cloud resolves above 1.38; only an operator who pinned lower gets a false.
func requiresConsumerType(microversion string) bool {
	if !isNumericMicroversion(microversion) {
		return true // "latest" (or unset) — assume the newest behaviour
	}
	return compareMicroversions(microversion, consumerTypeMicroversion) >= 0
}

// runProviderAllocationSet replaces the consumer's allocations wholesale, which
// is what placement's PUT does — there is no incremental form.
func runProviderAllocationSet(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	consumer string, f *allocationSetFlags, w io.Writer,
) error {
	// Placement 1.38 made consumer_type required, and it is not a value koc can
	// invent on the operator's behalf — it describes what the consumer *is*. Say
	// so here rather than letting placement answer with a schema dump.
	if f.consumerType == "" && requiresConsumerType(client.Microversion) {
		return fmt.Errorf("placement %s and later require a consumer type: pass --consumer-type "+
			"(e.g. INSTANCE or MIGRATION)", consumerTypeMicroversion)
	}
	byProvider := map[string]allocations.ProviderAllocationsOpts{}
	for _, spec := range f.specs {
		provider, resources, err := parseAllocationSpec(spec)
		if err != nil {
			return fmt.Errorf("parsing --allocation: %w", err)
		}
		existing, ok := byProvider[provider]
		if !ok {
			existing = allocations.ProviderAllocationsOpts{Resources: map[string]int{}}
		}
		for class, amount := range resources {
			existing.Resources[class] = amount
		}
		byProvider[provider] = existing
	}
	opts := allocations.UpdateOpts{
		Allocations:  byProvider,
		ProjectID:    f.projectID,
		UserID:       f.userID,
		ConsumerType: f.consumerType,
	}
	if err := allocations.Update(ctx, client, consumer, opts).ExtractErr(); err != nil {
		return fmt.Errorf("setting the allocations of consumer %s: %w", consumer, err)
	}
	return runProviderAllocationShow(ctx, client, o, consumer, w)
}

// parseAllocationSpec parses "rp=<uuid>,VCPU=2,MEMORY_MB=1024" into a provider
// and its resource amounts.
func parseAllocationSpec(spec string) (string, map[string]int, error) {
	var provider string
	resources := map[string]int{}
	for _, part := range strings.Split(spec, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		k, v, ok := strings.Cut(part, "=")
		if !ok {
			return "", nil, fmt.Errorf("expected key=value in %q", spec)
		}
		if k == "rp" {
			provider = v
			continue
		}
		n, err := strconv.Atoi(v)
		if err != nil {
			return "", nil, fmt.Errorf("%s in %q: %w", k, spec, err)
		}
		resources[k] = n
	}
	if provider == "" {
		return "", nil, fmt.Errorf("%q is missing rp=<provider-uuid>", spec)
	}
	if len(resources) == 0 {
		return "", nil, fmt.Errorf("%q names no resource amounts", spec)
	}
	return provider, resources, nil
}

func newProviderAllocationUnsetCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var providers, classes []string
	cmd := &cobra.Command{
		Use:   "unset <consumer-uuid>",
		Short: "Remove some or all of a consumer's allocations",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runProviderAllocationUnset(ctx, client, o, args[0], providers, classes, cmd.OutOrStdout())
		},
	}
	fl := cmd.Flags()
	fl.StringArrayVar(&providers, "provider", nil, "drop allocations against this provider UUID (repeatable)")
	fl.StringArrayVar(&classes, "resource-class", nil, "drop allocations of this resource class (repeatable)")
	return cmd
}

// runProviderAllocationUnset removes the named allocations by reading the
// current set, filtering it, and writing back the remainder — placement has no
// partial-delete endpoint. With neither flag it clears everything, matching
// upstream.
func runProviderAllocationUnset(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	consumer string, providers, classes []string, w io.Writer,
) error {
	if len(providers) == 0 && len(classes) == 0 {
		if err := allocations.Delete(ctx, client, consumer).ExtractErr(); err != nil {
			return fmt.Errorf("deleting the allocations of consumer %s: %w", consumer, err)
		}
		return nil
	}
	current, err := allocations.Get(ctx, client, consumer).Extract()
	if err != nil {
		return fmt.Errorf("reading the allocations of consumer %s: %w", consumer, err)
	}
	kept := keepAllocations(current.Allocations, providers, classes)
	if len(kept) == 0 {
		// Placement rejects a PUT with an empty allocations object; clearing the
		// last one is a DELETE.
		if err := allocations.Delete(ctx, client, consumer).ExtractErr(); err != nil {
			return fmt.Errorf("deleting the allocations of consumer %s: %w", consumer, err)
		}
		return nil
	}
	if err := allocations.Update(ctx, client, consumer, allocations.UpdateOpts{Allocations: kept}).ExtractErr(); err != nil {
		return fmt.Errorf("updating the allocations of consumer %s: %w", consumer, err)
	}
	return runProviderAllocationShow(ctx, client, o, consumer, w)
}

// keepAllocations computes the allocations that survive an unset: every
// provider the operator did not name, minus every resource class they did.
//
// Placement has no partial-delete endpoint — an update replaces the consumer's
// whole allocation set — so the survivors are derived client-side from what was
// just read. A provider left with no classes is dropped entirely rather than
// written back as an empty resources object, which placement rejects.
func keepAllocations(current map[string]allocations.ProviderAllocations,
	providers, classes []string,
) map[string]allocations.ProviderAllocationsOpts {
	kept := map[string]allocations.ProviderAllocationsOpts{}
	for providerID, alloc := range current {
		if contains(providers, providerID) {
			continue
		}
		resources := map[string]int{}
		for class, used := range alloc.Resources {
			if contains(classes, class) {
				continue
			}
			resources[class] = used
		}
		if len(resources) > 0 {
			kept[providerID] = allocations.ProviderAllocationsOpts{Resources: resources}
		}
	}
	return kept
}

func contains(haystack []string, needle string) bool {
	for _, s := range haystack {
		if s == needle {
			return true
		}
	}
	return false
}

// --- allocation candidate list ----------------------------------------------

// resourceQuery renders --resource values into placement's `resources` query
// parameter, which spells each entry CLASS:amount.
//
// The CLI spelling is CLASS=amount, matching upstream osc-placement
// (`--resource <resource_class>=<value>`). Passing that through untranslated is
// what placement rejects with:
//
//	Badly formed resources parameter. Expected resources query string parameter
//	in form: ?resources=VCPU:2,MEMORY_MB:1024. Got: VCPU=1.
//
// The colon form is accepted too, since it is what the wire wants and operators
// who read the error message reach for it.
func resourceQuery(resources []string) (string, error) {
	parts := make([]string, 0, len(resources))
	for _, r := range resources {
		class, amount, ok := strings.Cut(r, "=")
		if !ok {
			if class, amount, ok = strings.Cut(r, ":"); !ok {
				return "", fmt.Errorf("expected CLASS=amount, got %q", r)
			}
		}
		class, amount = strings.TrimSpace(class), strings.TrimSpace(amount)
		if class == "" || amount == "" {
			return "", fmt.Errorf("expected CLASS=amount, got %q", r)
		}
		parts = append(parts, class+":"+amount)
	}
	return strings.Join(parts, ","), nil
}

type candidateListFlags struct {
	resources []string
	required  []string
	memberOf  []string
	limit     int
}

func newAllocationCandidateCommand(a *auth.Options, o *output.Options) *cobra.Command {
	f := &candidateListFlags{}
	list := &cobra.Command{
		Use:   "list",
		Short: "List providers that can satisfy a resource request",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runAllocationCandidateList(ctx, client, o, f, cmd.OutOrStdout())
		},
	}
	fl := list.Flags()
	fl.StringArrayVar(&f.resources, "resource", nil, "required amount as CLASS=amount, e.g. VCPU=2 (repeatable)")
	fl.StringArrayVar(&f.required, "required", nil, "trait the provider must have; prefix ! to forbid (repeatable)")
	fl.StringArrayVar(&f.memberOf, "member-of", nil, "aggregate UUID the provider must belong to (repeatable)")
	fl.IntVar(&f.limit, "limit", 0, "maximum number of candidates to return")
	_ = list.MarkFlagRequired("resource")

	cmd := &cobra.Command{Use: "candidate", Short: "Inspect placement allocation candidates"}
	cmd.AddCommand(list)
	return cmd
}

func runAllocationCandidateList(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	f *candidateListFlags, w io.Writer,
) error {
	// Placement takes the amounts as one comma-separated `resources` parameter,
	// not as repeated ones, and separates class from amount with a colon.
	query, err := resourceQuery(f.resources)
	if err != nil {
		return fmt.Errorf("parsing --resource: %w", err)
	}
	opts := allocationcandidates.ListOpts{
		Resources: query,
		Required:  f.required,
		MemberOf:  f.memberOf,
		Limit:     f.limit,
	}
	pages, err := allocationcandidates.List(client, opts).AllPages(ctx)
	if err != nil {
		return fmt.Errorf("listing allocation candidates: %w", err)
	}
	candidates, err := allocationcandidates.ExtractAllocationCandidates(pages)
	if err != nil {
		return fmt.Errorf("parsing the allocation candidate list: %w", err)
	}
	t := output.Table{Columns: []string{"Resource Provider", colResourceClass, "Capacity", "Used"}}
	for providerID, summary := range candidates.ProviderSummaries {
		for class, res := range summary.Resources {
			t.Rows = append(t.Rows, []any{providerID, class, res.Capacity, res.Used})
		}
	}
	sortRowsByFirstColumn(t.Rows)
	return o.WriteList(w, t)
}

// --- resource usage show ----------------------------------------------------

func newResourceUsageCommand(a *auth.Options, o *output.Options) *cobra.Command {
	var userID string
	show := &cobra.Command{
		Use:   "show <project-id>",
		Short: "Show a project's resource usage across every provider",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runResourceUsageShow(ctx, client, o, args[0], userID, cmd.OutOrStdout())
		},
	}
	show.Flags().StringVar(&userID, "user-id", "", "narrow the usage to one user in the project")

	cmd := &cobra.Command{Use: "usage", Short: "Show placement resource usage"}
	cmd.AddCommand(show)
	return cmd
}

func runResourceUsageShow(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options,
	projectID, userID string, w io.Writer,
) error {
	got, err := usages.Get(ctx, client, usages.GetOpts{ProjectID: projectID, UserID: userID}).Extract()
	if err != nil {
		return fmt.Errorf("showing resource usage for project %s: %w", projectID, err)
	}
	t := output.Table{Columns: []string{colResourceClass, "Usage"}}
	for class, used := range got.Usages {
		t.Rows = append(t.Rows, []any{class, used})
	}
	sortRowsByFirstColumn(t.Rows)
	return o.WriteList(w, t)
}

// --- trait create / delete / show -------------------------------------------

func newTraitCreateCommand(a *auth.Options, o *output.Options) *cobra.Command {
	return &cobra.Command{
		Use:   "create <name>",
		Short: "Create a custom trait",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runTraitCreate(ctx, client, args[0])
		},
	}
}

func runTraitCreate(ctx context.Context, client *gophercloud.ServiceClient, name string) error {
	if err := traits.Create(ctx, client, name).ExtractErr(); err != nil {
		return fmt.Errorf("creating trait %s: %w", name, err)
	}
	return nil
}

func newTraitDeleteCommand(a *auth.Options, o *output.Options) *cobra.Command {
	return &cobra.Command{
		Use:   "delete <name> [<name> ...]",
		Short: "Delete custom trait(s)",
		Args:  cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runTraitDelete(ctx, client, args)
		},
	}
}

func runTraitDelete(ctx context.Context, client *gophercloud.ServiceClient, names []string) error {
	return batchdelete.Each(names, func(name string) error {
		if err := traits.Delete(ctx, client, name).ExtractErr(); err != nil {
			return fmt.Errorf("deleting trait %s: %w", name, err)
		}
		return nil
	})
}

func newTraitShowCommand(a *auth.Options, o *output.Options) *cobra.Command {
	return &cobra.Command{
		Use:   "show <name>",
		Short: "Show whether a trait exists",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.Validate(); err != nil {
				return err
			}
			ctx := cmd.Context()
			client, err := newPlacementClient(ctx, a)
			if err != nil {
				return err
			}
			return runTraitShow(ctx, client, o, args[0], cmd.OutOrStdout())
		},
	}
}

// runTraitShow reports existence. Placement's GET /traits/<name> has no body —
// it answers 204 when the trait exists and 404 when it does not — so the name
// is echoed rather than any server-provided field.
func runTraitShow(ctx context.Context, client *gophercloud.ServiceClient, o *output.Options, name string, w io.Writer) error {
	if err := traits.Get(ctx, client, name).ExtractErr(); err != nil {
		return fmt.Errorf("showing trait %s: %w", name, err)
	}
	return o.WriteSingle(w, []string{"name"}, []any{name})
}

// sortRowsByFirstColumn keeps output stable: several of these results come from
// a map, whose iteration order would otherwise vary run to run.
func sortRowsByFirstColumn(rows [][]any) {
	for i := 1; i < len(rows); i++ {
		for j := i; j > 0 && rowKey(rows[j]) < rowKey(rows[j-1]); j-- {
			rows[j], rows[j-1] = rows[j-1], rows[j]
		}
	}
}

func rowKey(row []any) string {
	if len(row) == 0 {
		return ""
	}
	return fmt.Sprintf("%v|%v", row[0], row[min(1, len(row)-1)])
}
