#!/usr/bin/env python3
"""Regenerate internal/cli/network/upstream_flags_data_test.go.

The table is read from python-openstackclient's own argparse parsers, which are
the authoritative flag list (its docs lag the code, and opendev.org is
unreachable from CI/agent environments; PyPI is not). Needs network once:

    python3 -m venv /tmp/osc && /tmp/osc/bin/pip install python-openstackclient==<ver>
    /tmp/osc/bin/python scripts/network-flag-table.py > internal/cli/network/upstream_flags_data_test.go
    gofmt -w internal/cli/network/upstream_flags_data_test.go   # Go 1.27's gofmt

Not part of the build: the air-gap invariant is unaffected.
"""
import sys
from importlib.metadata import entry_points, version
from unittest import mock

# Pagination and cliff's -f shell --variable are not network surface.
SKIP = {'--variable', '--limit', '--marker', '--max-items'}
# cliff/osc-lib output options every command inherits.
OUTPUT = {'--format', '--column', '--noindent', '--prefix', '--max-width', '--fit-width',
          '--print-empty', '--sort-column', '--sort-ascending', '--sort-descending', '--quote',
          '--help'}

app = mock.MagicMock()
app.client_manager.is_network_endpoint_enabled.return_value = True
rows = []
for ep in sorted(entry_points(group='openstack.network.v2'), key=lambda e: e.name):
    parser = ep.load()(app, None).get_parser('openstack ' + ep.name.replace('_', ' '))
    opts = []
    for action in parser._actions:
        longs = [s for s in action.option_strings if s.startswith('--')]
        if not longs or set(action.option_strings) & OUTPUT or longs[0] in SKIP:
            continue
        opts.append(longs)
    opts.sort()
    items = ', '.join('{' + ', '.join('"%s"' % a[2:] for a in al) + '}' for al in opts)
    rows.append('\t"%s": {%s},' % (ep.name.replace('_', ' '), items))

print(f'''package network

// Code generated by scripts/network-flag-table.py from python-openstackclient
// {version("python-openstackclient")}'s own argparse parsers. DO NOT EDIT by hand: re-run it when the
// baseline moves.
//
// upstreamNetworkFlags maps each openstack.network.v2 command to its long
// options. Each inner slice is one option's aliases; koc satisfies the option
// when it registers any of them. Pagination (--limit/--marker/--max-items) and
// cliff's shell-formatter --variable are left out.
var upstreamNetworkFlags = map[string][][]string{{''')
print('\n'.join(rows))
print('}')
